/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica5f;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author José Alfredo Moreno Suárez
 */
public class Practica5FinalEntrenamiento extends javax.swing.JFrame {
    
    /**
     * Creates new form Practica5FinalEntrenamiento
     */
    public Practica5FinalEntrenamiento() {
        initComponents();
        gAlgoritmos();//Funcion que agrupa botones para evitar multi check
        rc = new RCompartido();//Crea el RC
        //Cambiamos nombres, asignamos RC y areas a los hilos
        creaHilos();        
        btnKill.setEnabled(false);
    }
    public void creaHilos(){
        t1 = new Hilo(area1,rc);
        t1.setName("Torta1");
        t2 = new Hilo(area2,rc);
        t2.setName("Torta2");
        t3 = new Hilo(area3,rc);
        t3.setName("Torta3");
        t4 = new Hilo(area4,rc);
        t4.setName("Torta4");
    }
    public void gAlgoritmos(){//Funcion que evita multichecks
        algoritmos = new ButtonGroup();
        algoritmos.add(CC);
        algoritmos.add(DI);
        algoritmos.add(VC);
        algoritmos.add(DK);
        algoritmos.add(DJ);
        algoritmos.add(MX);
    }
    public void cambioAlgoritmo(int i){
        t1.setAlgoritmo(i);
        t2.setAlgoritmo(i);
        t3.setAlgoritmo(i);
        t4.setAlgoritmo(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnKill = new javax.swing.JButton();
        btnCambio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        area3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        area4 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        salida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CC = new javax.swing.JRadioButtonMenuItem();
        DI = new javax.swing.JRadioButtonMenuItem();
        VC = new javax.swing.JRadioButtonMenuItem();
        DK = new javax.swing.JRadioButtonMenuItem();
        DJ = new javax.swing.JRadioButtonMenuItem();
        MX = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel5.setText("PANEL DE CONTROL");

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnKill.setText("KILL - 9");
        btnKill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKillActionPerformed(evt);
            }
        });

        btnCambio.setText("CAMBIO");
        btnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(btnCrear)
                .addGap(49, 49, 49)
                .addComponent(btnKill)
                .addGap(33, 33, 33)
                .addComponent(btnCambio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        area1.setEditable(false);
        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        area2.setEditable(false);
        area2.setColumns(20);
        area2.setRows(5);
        jScrollPane2.setViewportView(area2);

        area3.setEditable(false);
        area3.setColumns(20);
        area3.setRows(5);
        jScrollPane3.setViewportView(area3);

        area4.setEditable(false);
        area4.setColumns(20);
        area4.setRows(5);
        jScrollPane4.setViewportView(area4);

        jLabel1.setText("PLATO 1");

        jLabel2.setText("PLATO 2");

        jLabel3.setText("PLATO 3");

        jLabel4.setText("PLATO 4");

        jMenu1.setText("File");

        salida.setText("Exit");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        jMenu1.add(salida);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Algorithms");

        CC.setSelected(true);
        CC.setText("Condiciones Competencias");
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });
        jMenu2.add(CC);

        DI.setSelected(true);
        DI.setText("Desactivacion por interrupciones");
        DI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIActionPerformed(evt);
            }
        });
        jMenu2.add(DI);

        VC.setSelected(true);
        VC.setText("Variable Cerradura");
        VC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VCActionPerformed(evt);
            }
        });
        jMenu2.add(VC);

        DK.setSelected(true);
        DK.setText("Dekker");
        DK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DKActionPerformed(evt);
            }
        });
        jMenu2.add(DK);

        DJ.setSelected(true);
        DJ.setText("Dijkstra");
        DJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DJActionPerformed(evt);
            }
        });
        jMenu2.add(DJ);

        MX.setSelected(true);
        MX.setText("Mutex");
        MX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MXActionPerformed(evt);
            }
        });
        jMenu2.add(MX);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if(banStop){
            creaHilos();
            System.out.println("Creo hilos");
        }
        banStop=false;
        if(CC.isSelected()){
            cambioAlgoritmo(0);
        }
        if(DI.isSelected()){
            cambioAlgoritmo(1);
        }
        if(VC.isSelected()){
            cambioAlgoritmo(2);
        }
        if(DK.isSelected()){
            cambioAlgoritmo(3);
        }
        if(DJ.isSelected()){
            cambioAlgoritmo(4);
        }
        if(MX.isSelected()){
            cambioAlgoritmo(5);
        }
        limpiaTexto();
        t1.start();
        t2.start();
        t3.start();
        t4.start();
        btnCrear.setEnabled(false);
        if(CC.isSelected())
            btnKill.setEnabled(false);
        else
            btnKill.setEnabled(true);
    }//GEN-LAST:event_btnCrearActionPerformed

    public void limpiaTexto(){
        area1.setText("");
        area2.setText("");
        area3.setText("");
        area4.setText("");
    }
    
    private void btnKillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKillActionPerformed
        int HiloRand = (int)(Math.random()*4);
        switch(HiloRand){
            case 0:
                try{
                    t1.setDead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null,"Error al suspender el hilo");}
                break;
            case 1:
                try{
                    t2.setDead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null,"Error al suspender el hilo");}
                break;
            case 2:
                try{
                    t3.setDead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null,"Error al suspender el hilo");}
                break;
            case 3:
                try{
                    t4.setDead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null,"Error al suspender el hilo");}
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnKillActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    public void mataResto(){
        if(!t1.isDead())
            t1.stop();
        if(!t2.isDead())
            t2.stop();
        if(!t3.isDead())
            t3.stop();
        if(!t4.isDead())
            t4.stop();
        banStop=true;
    }
    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_CCActionPerformed

    private void btnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioActionPerformed
        mataResto();
        btnKill.setEnabled(false);
    }//GEN-LAST:event_btnCambioActionPerformed

    private void DIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIActionPerformed
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_DIActionPerformed

    private void VCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VCActionPerformed
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_VCActionPerformed

    private void DKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DKActionPerformed
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_DKActionPerformed

    private void DJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DJActionPerformed
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_DJActionPerformed

    private void MXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MXActionPerformed
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_MXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica5FinalEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica5FinalEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica5FinalEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica5FinalEntrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica5FinalEntrenamiento().setVisible(true);
            }
        });
    }
    //Variables personales
    private Hilo t1,t2, t3, t4;
    private RCompartido rc;
    private VCerradura cd;
    private ButtonGroup algoritmos;
    private boolean banStop = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem CC;
    private javax.swing.JRadioButtonMenuItem DI;
    private javax.swing.JRadioButtonMenuItem DJ;
    private javax.swing.JRadioButtonMenuItem DK;
    private javax.swing.JRadioButtonMenuItem MX;
    private javax.swing.JRadioButtonMenuItem VC;
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JTextArea area3;
    private javax.swing.JTextArea area4;
    private javax.swing.JButton btnCambio;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnKill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuItem salida;
    // End of variables declaration//GEN-END:variables
}
